#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            ref class VisualState;
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class RelativePanel;
                ref class TextBox;
                ref class Button;
            }
        }
    }
}

namespace FiveCardDraw_UWP_App
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::VisualState^ WideState;
        private: ::Windows::UI::Xaml::Controls::Grid^ opponent_grid;
        private: ::Windows::UI::Xaml::Controls::Grid^ player_grid;
        private: ::Windows::UI::Xaml::Controls::RelativePanel^ hud_panel;
        private: ::Windows::UI::Xaml::Controls::TextBox^ Winner_Text;
        private: ::Windows::UI::Xaml::Controls::Button^ Draw_button;
        private: ::Windows::UI::Xaml::Controls::TextBox^ User_Card1;
        private: ::Windows::UI::Xaml::Controls::TextBox^ User_Card2;
        private: ::Windows::UI::Xaml::Controls::TextBox^ User_Card3;
        private: ::Windows::UI::Xaml::Controls::TextBox^ User_Card4;
        private: ::Windows::UI::Xaml::Controls::TextBox^ User_Card5;
        private: ::Windows::UI::Xaml::Controls::Button^ User_Button1;
        private: ::Windows::UI::Xaml::Controls::Button^ User_Button2;
        private: ::Windows::UI::Xaml::Controls::Button^ User_Button3;
        private: ::Windows::UI::Xaml::Controls::Button^ User_Button4;
        private: ::Windows::UI::Xaml::Controls::Button^ User_Button5;
        private: ::Windows::UI::Xaml::Controls::TextBox^ player_box;
        private: ::Windows::UI::Xaml::Controls::TextBox^ Opponent_Card1;
        private: ::Windows::UI::Xaml::Controls::TextBox^ Opponent_Card2;
        private: ::Windows::UI::Xaml::Controls::TextBox^ Opponent_Card3;
        private: ::Windows::UI::Xaml::Controls::TextBox^ Opponent_Card4;
        private: ::Windows::UI::Xaml::Controls::TextBox^ Opponent_Card5;
        private: ::Windows::UI::Xaml::Controls::Button^ OP_Card_Button1;
        private: ::Windows::UI::Xaml::Controls::Button^ OP_Card_Button2;
        private: ::Windows::UI::Xaml::Controls::Button^ OP_Card_Button3;
        private: ::Windows::UI::Xaml::Controls::Button^ OP_Card_Button4;
        private: ::Windows::UI::Xaml::Controls::Button^ OP_Card_Button5;
        private: ::Windows::UI::Xaml::Controls::TextBox^ opponent_box;
    };
}

