//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MainPage.xaml.h"

void ::FiveCardDraw_UWP_App::MainPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::FiveCardDraw_UWP_App::MainPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                ::Windows::UI::Xaml::Controls::Button^ element1 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(element1))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::FiveCardDraw_UWP_App::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::DrawButton_Click);
            }
            break;
        case 2:
            {
                this->Winner_Text = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 3:
            {
                this->User_Card1 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 4:
            {
                this->User_Card2 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 5:
            {
                this->User_Card3 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 6:
            {
                this->User_Card4 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 7:
            {
                this->User_Card5 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 8:
            {
                this->User_Button1 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            }
            break;
        case 9:
            {
                this->User_Button2 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            }
            break;
        case 10:
            {
                this->User_Button3 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            }
            break;
        case 11:
            {
                this->User_Button4 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            }
            break;
        case 12:
            {
                this->User_Button5 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            }
            break;
        case 13:
            {
                this->player_box = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 14:
            {
                this->Opponent_Card1 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 15:
            {
                this->Opponent_Card2 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 16:
            {
                this->Opponent_Card3 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 17:
            {
                this->Opponent_Card4 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 18:
            {
                this->Opponent_Card5 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 19:
            {
                this->OP_Card_Button1 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            }
            break;
        case 20:
            {
                this->OP_Card_Button2 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            }
            break;
        case 21:
            {
                this->OP_Card_Button3 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            }
            break;
        case 22:
            {
                this->OP_Card_Button4 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            }
            break;
        case 23:
            {
                this->OP_Card_Button5 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            }
            break;
        case 24:
            {
                this->opponent_box = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::FiveCardDraw_UWP_App::MainPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


